### ISSUE TITLE
Geographical

### ISSUE THREAD

**Issue by a-reyhan** [course-dprep/team-project-team-13#5]
Which region do we want to focus on?

**Comment by C-Inzirillo** [comment]
IMDb has no geographical limitation, and it shows data from all over the world.
Since the 1.1 challenge (Exploring the Universe of Potential Web Sources) says to Broaden geographic search criteria, I'll suggest expanding our geographical universe as much as possible.
To simplify our work. I'll also suggest comparing data  between each country of Europe (e.g. Nord vs. Sud, East vs. West) or among continents (Europe vs. America)

**Comment by sjvangoor** [comment]
Issue became irrelevant as we are now using a different approach to the group project, using a different RQ.
